### ISSUE TITLE
Switch back to Linux runners

### ISSUE THREAD

**Issue by IncPlusPlus** [IncPlusPlus/titanfall2-rp#84]
As it turns out, there's a bug that causes exe files to be missing the metadata specified in the `csproj` file. This was discovered and temporarily fixed with #83.

This issue is blocked by dotnet/runtime#3828

**Comment by IncPlusPlus** [comment]
Now that the auto updater introduced a `FrameworkReference` into the csproj, this will no longer build on Linux.

**Comment by RobThree** [comment]
> Now that the auto updater introduced a `FrameworkReference` into the csproj, this will no longer build on Linux.

What does that mean? What do I have to do to have my icons and metadata in my executables? What is this `FrameworkReference` you're referring to and where can I find more about it? Is this released already or, if not, when will it be?

**Comment by IncPlusPlus** [comment]
Somebody commented here but deleted it. Here's what they said:

>>Now that the auto updater introduced a FrameworkReference into the csproj, this will no longer build on Linux.

>What does that mean? What do I have to do to have my icons and metadata in my executables? What is this FrameworkReference you're referring to and where can I find more about it? Is this released already or, if not, when will it be?

Um. I think you commented in the wrong repo, buddy.

**Comment by RobThree** [comment]
That's why I deleted it buddy.
